// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9XkIQFcsu4PJZ4Uv0iX3IFbH6AF1Axyk',
    appId: '1:699055440569:web:1a6820ccb037e0ff94d168',
    messagingSenderId: '699055440569',
    projectId: 'catalogo-de-peliculas-suv',
    authDomain: 'catalogo-de-peliculas-suv.firebaseapp.com',
    storageBucket: 'catalogo-de-peliculas-suv.firebasestorage.app',
    measurementId: 'G-25TEX2S1X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSBuQX--0MoBzjbmgB87X0DQ_fIle0lK0',
    appId: '1:699055440569:android:b7ff6ef91ecdfb4f94d168',
    messagingSenderId: '699055440569',
    projectId: 'catalogo-de-peliculas-suv',
    storageBucket: 'catalogo-de-peliculas-suv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANKriMAcOvUcVHbZnc2H3d4CNpCdkeG4s',
    appId: '1:699055440569:ios:bafd891ca1499a8394d168',
    messagingSenderId: '699055440569',
    projectId: 'catalogo-de-peliculas-suv',
    storageBucket: 'catalogo-de-peliculas-suv.firebasestorage.app',
    iosBundleId: 'com.example.nuevaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANKriMAcOvUcVHbZnc2H3d4CNpCdkeG4s',
    appId: '1:699055440569:ios:bafd891ca1499a8394d168',
    messagingSenderId: '699055440569',
    projectId: 'catalogo-de-peliculas-suv',
    storageBucket: 'catalogo-de-peliculas-suv.firebasestorage.app',
    iosBundleId: 'com.example.nuevaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9XkIQFcsu4PJZ4Uv0iX3IFbH6AF1Axyk',
    appId: '1:699055440569:web:86df799771c8813094d168',
    messagingSenderId: '699055440569',
    projectId: 'catalogo-de-peliculas-suv',
    authDomain: 'catalogo-de-peliculas-suv.firebaseapp.com',
    storageBucket: 'catalogo-de-peliculas-suv.firebasestorage.app',
    measurementId: 'G-CXQCHE67TL',
  );
}
